project:
  type: website

website:
  title: "Assessing Climate Change in the Southeastern Utah Group National Parks"
  navbar:
    left:
      - href: code/natural_bridges.qmd
        text: Article
      - href: code/repo.qmd
        text: Code

format:
  html:
    theme: cosmo
    toc: true



